# Generated by Django 3.2.7 on 2021-09-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210927_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='level',
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
