# Generated by Django 3.2.7 on 2021-10-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211010_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque fermentum finibus neque, gravida vestibulum lectus rutrum a. Aliquam ac nibh .', max_length=400),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='place_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
