# Generated by Django 3.2.7 on 2021-11-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='picture_small',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
