# Generated by Django 3.2.7 on 2021-11-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211105_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
