# Generated by Django 3.2.7 on 2021-09-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.socialnetwork'),
            preserve_default=False,
        ),
    ]
