# Generated by Django 3.2.7 on 2021-09-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_social_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social_network',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_network',
            field=models.ManyToManyField(to='account.SocialNetwork'),
        ),
    ]
