# Generated by Django 3.2.7 on 2021-09-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210929_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='icon',
            field=models.CharField(choices=[('Instagram', 'I'), ('Facebook', 'F'), ('LinkedIn', 'L'), ('Twitter', 'T'), ('Pinterest', 'P'), ('Tumblr', 'T'), ('Flickr', 'F'), ('Reddit', 'R')], max_length=20),
        ),
    ]
