# Generated by Django 3.2.7 on 2021-10-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_socialnetwork_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='icon',
            field=models.CharField(choices=[('fa fa-instagram', 'Instagram'), ('fa fa-facebook', 'Facebook'), ('fa fa-linkedin', 'LinkedIn'), ('fa fa-twitter', 'Twitter'), ('fa fa-pinterest', 'Pinterest'), ('fa fa-tumblr', 'Tumblr'), ('fa fa-flickr', 'Flickr'), ('fa fa-reddit', 'Reddit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(auto_now=True),
        ),
    ]
