# Generated by Django 3.2.7 on 2021-10-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20211023_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_title',
            field=models.TextField(max_length=500),
        ),
    ]
