# Generated by Django 3.2.7 on 2021-11-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20211024_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/CV.pdf', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/pp.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_small',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/p.jpg', null=True, upload_to=''),
        ),
    ]
